# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'whatever' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for whatever
  pod 'Firebase'
  target 'whateverTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'whateverUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
